CREATE TABLE comment(
	comment_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	element_name VARCHAR(250) NOT NULL,
	comment_title VARCHAR(250) NOT NULL,
	comment_text VARCHAR(250) NOT NULL,
	date_create DATE NOT NULL,
	date_to_fix DATE NOT NULL,
	executor VARCHAR(250) NOT NULL
);

ALTER TABLE comment
ADD COLUMN status VARCHAR(50) DEFAULT 'AWAIT' CHECK (status IN ('AWAIT', 'PROCESS', 'COMPLETE'));

ALTER TABLE comment
ADD COLUMN camera_position JSONB DEFAULT '{}';

ALTER TABLE comment
ADD COLUMN camera_rotation JSONB DEFAULT '{}';

ALTER TABLE comment
ADD COLUMN position JSONB DEFAULT '{}';

ALTER TABLE comment
ADD COLUMN clipper_positions JSONB DEFAULT '{}';

ALTER TABLE comment
ADD COLUMN file_path VARCHAR NOT NULL DEFAULT '';

ALTER TABLE comment
ADD COLUMN model_name VARCHAR NOT NULL DEFAULT '';

CREATE TABLE decoration (
	decoration_name VARCHAR PRIMARY KEY,
	decoration_type VARCHAR(250) NOT NULL,
	quantity int NOT NULL,
	room_id VARCHAR NOT NULL,
	status VARCHAR(50) DEFAULT 'AWAIT' CHECK (status IN ('AWAIT', 'APPROVE', 'REFUSED'))
);